name: Release

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  deploy_docs:
    name: Deploy docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
          pip install .
      - name: Build docs
        run: sphinx-build -b html docs public
        env:
          NUCLEI_TOKEN: ${{ secrets.NUCLEI_TOKEN }}
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
  deploy_pypi:
    needs: deploy_docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install setuptools twine build
      - name: Build & Release
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m build
          twine upload --skip-existing dist/*
